spring:
  profiles: dev
  application:
    name: eureka-client1
server:
  port: 8762

test:
  auto:
    update: haha
spring:
  profiles: test
  application:
    name: eureka-client2
server:
  port: 8762

test:
  auto:
    update: haha222

  
